#!/bin/sh
set -eu

HERE=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
SUPERVISOR=$HERE/package/leftovers-guest-supervisor/src/guest_supervisor.c
INTERPRETER=$HERE/package/leftovers-guest-supervisor/src/guest_interpreter.c
EARLY_INIT=$HERE/package/leftovers-guest-supervisor/src/early_init.c
DEFCONFIG=$HERE/configs/leftovers_strict_vm_defconfig

test -f "$HERE/SOURCES.lock.json"
python3 "$HERE/verify-sources.py"
python3 "$HERE/release.py" validate-locks
test -f "$SUPERVISOR"
test -f "$INTERPRETER"
test -f "$EARLY_INIT"
test -f "$DEFCONFIG"
grep -q 'BR2_LINUX_KERNEL_CUSTOM_REPO_VERSION="669dc96e243e422e7404bb98be00d527bafc0a96"' "$DEFCONFIG"
grep -q 'CONFIG_NET=n' "$HERE/board/leftovers/linux.fragment"
grep -q 'CONFIG_SECURITY_LANDLOCK=y' "$HERE/board/leftovers/linux.fragment"
grep -q 'SYS_pivot_root' "$EARLY_INIT"
grep -q 'mount("/dev/vda", "/newroot", "ext4", MS_RDONLY' "$EARLY_INIT"
grep -q 'PR_SET_NO_NEW_PRIVS' "$SUPERVISOR"
grep -q 'SECCOMP_MODE_FILTER' "$SUPERVISOR"
grep -q 'SYS_landlock_restrict_self' "$SUPERVISOR"
grep -q 'memory.max' "$SUPERVISOR"
grep -q 'pids.max' "$SUPERVISOR"
grep -q 'cpu.max' "$SUPERVISOR"
grep -q 'cgroup.subtree_control' "$SUPERVISOR"
grep -q 'leftovers.request=/dev/vdc' "$SUPERVISOR"
grep -q 'leftovers.scratch=/dev/vdb' "$SUPERVISOR"
grep -q 'SYS_close_range' "$SUPERVISOR"
grep -q 'descriptor_table_is_empty' "$SUPERVISOR"
grep -q 'RLIMIT_NOFILE' "$SUPERVISOR"
grep -q 'RLIMIT_FSIZE' "$SUPERVISOR"
grep -q 'RLIMIT_CORE' "$SUPERVISOR"
grep -q 'RLIMIT_CPU' "$SUPERVISOR"
grep -q 'setitimer' "$SUPERVISOR"
grep -q 'block_device_inventory_is_exact' "$SUPERVISOR"
grep -q 'limited_device_node_inventory_is_exact' "$SUPERVISOR"
grep -q 'make_limited_block_node' "$SUPERVISOR"
grep -q '"tmpfs",' "$SUPERVISOR"
grep -q '"/dev",' "$SUPERVISOR"
grep -q 'BLKROGET' "$SUPERVISOR"
grep -q 'LANDLOCK_ACCESS_FS_TRUNCATE' "$SUPERVISOR"
grep -q 'LANDLOCK_CREATE_RULESET_VERSION' "$SUPERVISOR"
grep -q '#include "guest_interpreter.c"' "$SUPERVISOR"
grep -q 'if (false)' "$SUPERVISOR"
grep -q 'LFR_HEADER_BYTES' "$INTERPRETER"
grep -q 'lfr_parse_request' "$INTERPRETER"
grep -q 'lfr_parse_action_batch' "$INTERPRETER"
grep -q 'lfr_parse_one_action' "$INTERPRETER"
grep -q 'lfr_open_beneath' "$INTERPRETER"
grep -q 'RESOLVE_BENEATH' "$INTERPRETER"
grep -q 'RESOLVE_NO_MAGICLINKS' "$INTERPRETER"
grep -q 'RESOLVE_NO_SYMLINKS' "$INTERPRETER"
grep -q 'O_NOFOLLOW' "$INTERPRETER"
grep -q 'BLKGETSIZE64' "$INTERPRETER"
grep -q 'BLKROGET' "$INTERPRETER"
grep -q 'S_ISBLK' "$INTERPRETER"
grep -q 'prior_obs' "$INTERPRETER"
grep -q 'repo-tree-safety-v1' "$INTERPRETER"
grep -q 'repo-root-regular-v1' "$INTERPRETER"
grep -q 'lfr_apply_exact_controller_patch' "$INTERPRETER"
grep -q 'lfr_emit_bounded_result' "$INTERPRETER"
grep -q 'LFR_MAX_ACTIONS' "$INTERPRETER"
grep -q 'LFR_MAX_TREE_DEPTH' "$INTERPRETER"
grep -q 'LFR_MAX_REPOSITORY_BYTES' "$INTERPRETER"
grep -q 'entry = readdir(directory)' "$INTERPRETER"
grep -q 'if (errno != 0)' "$INTERPRETER"
! grep -q 'lfr_json_contains_exact' "$INTERPRETER"
! grep -q 'lfr_hex_digest_present' "$INTERPRETER"
! grep -Eq '\b(system|popen|execlp|execvp|execve)\s*\(' "$SUPERVISOR"
! grep -Eq '\b(system|popen|execlp|execvp|execve)\s*\(' "$INTERPRETER"
echo 'strict guest static policy checks passed'
