#!/bin/sh
# Run only inside the digest-pinned, disposable builder selected by BUILD.lock.
# The fetch phase is the sole networked phase.  The build phase is network-none
# and returns an unsigned candidate only; it never installs boot artifacts.
set -eu

phase=${1:?expected fetch or build}
workspace=/workspace
guest=$workspace/vm/guest
sources=/work/sources
output=/work/output
downloads=/work/download-cache
gnupg_home=/tmp/leftovers-gnupg
git_home=/tmp/leftovers-git-home

case "$phase" in
  fetch|build) ;;
  *) echo "unknown guest builder phase" >&2; exit 64 ;;
esac

test -d "$workspace/.git"
test -f "$guest/release.py"
python3 "$guest/release.py" release-readiness --workspace "$workspace"

prepare_gnupg() {
  rm -rf "$gnupg_home"
  rm -rf "$git_home"
  mkdir -m 700 "$gnupg_home"
  mkdir -m 700 "$git_home"
  cp -a "$guest/trusted-keys/." "$gnupg_home/"
  chmod -R go-rwx "$gnupg_home"
}

verify_sources() {
  prepare_gnupg
  python3 "$guest/release.py" verify-checkouts \
    --workspace "$workspace" \
    --buildroot "$sources/buildroot" \
    --linux "$sources/linux-stable" \
    --gnupg-home "$gnupg_home" \
    --output "$output/source-verification-$phase.json" \
    --output-root "$output"
}

source_field() {
  python3 "$guest/release.py" source-field --workspace "$workspace" \
    --name "$1" --field "$2"
}

git_safe() {
  env -i PATH="$PATH" LC_ALL=C HOME=/nonexistent GIT_CONFIG_NOSYSTEM=1 \
    GIT_CONFIG_SYSTEM=/dev/null GIT_CONFIG_GLOBAL=/dev/null GIT_TERMINAL_PROMPT=0 \
    git -c core.hooksPath=/dev/null -c core.fsmonitor=false -c core.autocrlf=false \
      -c credential.helper= "$@"
}

source_epoch() {
  value=$(python3 -c 'import json; print(json.load(open("/workspace/vm/guest/BUILD.lock.json", encoding="utf-8"))["reproducibility"]["source_date_epoch"])')
  case "$value" in
    ''|*[!0-9]*) echo "unsafe SOURCE_DATE_EPOCH" >&2; exit 65 ;;
  esac
  printf '%s' "$value"
}

configure_buildroot() {
  mkdir -p "$output/build" "$downloads"
  make -C "$sources/buildroot" \
    BR2_EXTERNAL="$guest" \
    O="$output/build" \
    leftovers_strict_vm_defconfig
  cat > "$output/build/local.mk" <<'EOF'
# Generated by Leftovers' container-only guest builder. Do not edit.
LINUX_OVERRIDE_SRCDIR = /work/sources/linux-stable
EOF
  test "$(cat "$output/build/local.mk")" = "# Generated by Leftovers' container-only guest builder. Do not edit.
LINUX_OVERRIDE_SRCDIR = /work/sources/linux-stable"
}

if test "$phase" = fetch; then
  test ! -e "$sources/buildroot"
  test ! -e "$sources/linux-stable"
  mkdir -p "$sources" "$output" "$downloads"
  python3 "$guest/release.py" verify-remote --workspace "$workspace"
  buildroot_url=$(source_field buildroot repository)
  buildroot_ref=$(source_field buildroot ref)
  linux_url=$(source_field linux-stable repository)
  linux_ref=$(source_field linux-stable ref)
  git_safe init -q "$sources/buildroot"
  git_safe -C "$sources/buildroot" remote add origin "$buildroot_url"
  git_safe -C "$sources/buildroot" fetch --depth=1 --no-tags origin "$buildroot_ref:$buildroot_ref"
  git_safe -C "$sources/buildroot" checkout --detach "$buildroot_ref"
  git_safe init -q "$sources/linux-stable"
  git_safe -C "$sources/linux-stable" remote add origin "$linux_url"
  git_safe -C "$sources/linux-stable" fetch --depth=1 --no-tags origin "$linux_ref:$linux_ref"
  git_safe -C "$sources/linux-stable" checkout --detach "$linux_ref"
  verify_sources
  configure_buildroot
  SOURCE_DATE_EPOCH=$(source_epoch) BR2_DL_DIR="$downloads" \
    make -C "$sources/buildroot" BR2_EXTERNAL="$guest" O="$output/build" source
  exit 0
fi

test -d "$sources/buildroot/.git"
test -d "$sources/linux-stable/.git"
test -f "$output/build/local.mk"
verify_sources
test "$(cat "$output/build/local.mk")" = "# Generated by Leftovers' container-only guest builder. Do not edit.
LINUX_OVERRIDE_SRCDIR = /work/sources/linux-stable"
SOURCE_DATE_EPOCH=$(source_epoch) BR2_DL_DIR="$downloads" \
  make -C "$sources/buildroot" BR2_EXTERNAL="$guest" O="$output/build"

compiler="$output/build/host/bin/aarch64-buildroot-linux-musl-gcc"
test -x "$compiler"
"$compiler" --version > "$output/compiler-version.txt"
python3 "$guest/release.py" emit-build-metadata \
  --workspace "$workspace" \
  --build-context "$guest" \
    --compiler "aarch64-buildroot-linux-musl-gcc" \
    --compiler-version "$output/compiler-version.txt" \
    --output "$output/build-metadata.json" \
    --output-root "$output"
python3 "$guest/release.py" emit-sbom --workspace "$workspace" \
  --output "$output/sbom.json" --output-root "$output"
python3 "$guest/release.py" emit-provenance \
  --workspace "$workspace" \
  --kernel "$output/build/images/Image" \
  --initrd "$output/build/images/rootfs.cpio.gz" \
  --root-disk "$output/build/images/rootfs.ext2" \
    --build-metadata "$output/build-metadata.json" \
    --sbom "$output/sbom.json" \
    --output "$output/provenance.json" \
    --artifact-root "$output"
python3 "$guest/release.py" generate-candidate \
  --workspace "$workspace" \
  --kernel "$output/build/images/Image" \
  --initrd "$output/build/images/rootfs.cpio.gz" \
  --root-disk "$output/build/images/rootfs.ext2" \
  --build-metadata "$output/build-metadata.json" \
    --sbom "$output/sbom.json" \
    --provenance "$output/provenance.json" \
    --output "$output/candidate" \
    --artifact-root "$output"
echo "unsigned guest candidate created; external provenance verification is mandatory" >&2
exit 78
